name: buildAssist
main: com.github.unchama.buildassist.BuildAssist
version: 0.0.0

commands:
  fly:
      description: This is a fly command.
      usage: /<command> <stop/count>
      permission: multiseichiplugin.build
      permission-message: You don't have <permission>